### PR TITLE
Bootstrap 5 Renderer

### PR DESCRIPTION
**Pull request by coolacid**
This PR adds a new `BootStrapRenderer` which provides the necessary render functions to work with Bootstrap 5. 

This is tested using the `bootstrap_flask` python package. 

When initializing nav, you pass a `bootstrap=True` to the init. 

```
nav = Nav()
nav.init_app(app, bootstrap=True)
```

### CODE REVIEW

**Comment by coolacid** [comment]
Refactored as much as I can to meet flake8 requirements. Not sure where to go from here.

**Comment by qs5779** [comment]
Seems like only two minor issues, left. I will see if I can tweak them. Curiously though, can you explain why this is needed a little better? I use this in a flask app of mine that also uses the flask_bootstrap package and it is working for me.

**Comment by coolacid** [comment]
Thanks. If I remember correctly, the CSS for Bootstrap 5 changed a bunch of items causing the drop down sub navs to not work? I honestly started the work a while ago and only now put the final touches to get it all working as expected.

**Comment by qs5779** [comment]
Closing.

**Comment by qs5779** [comment]
First of all, I apologize. I thought we had discussed this earlier, but I must have confused it with another PR. I closed it mainly because I don't know off the top of my head how to implement the request you are making, however if you do I would happily accept a PR that doesn't break any existing functionality.

**Comment by coolacid** [comment]
This doesn't break any current functionality. There is a configuration bool to turn on and use this code path.

**Comment by qs5779** [comment]
When I build with your previous PR and tested with one of my flask projects, my navigation did not work correctly regardless of whether I specified bootstrap  = True, or bootstrap = False.

**Comment by jaskenda-talos** [comment]
I only have this one PR. 

I'll test again using the provided sample to see if I can see why it would not be working. Mind re-opening this PR for continued work?

**Comment by coolacid** [comment]
I only have the one PR. I'll test with the existing example code to see if I can see why it wouldn't be working.

Mind re-opening for work to continue?

**Comment by coolacid** [comment]
So, I just tried to use the example code out of the box as it sits in this repo. There is no nav bar, just the nav objects. This is because the example code doesn't include any CSS code what so ever to provide drop down or nav bar solutions. I'll investigate getting a working example working and apply to this PR.

**Pull request closed without merging**
