### PR TITLE
Bootstrap 5 Renderer

### PR DESCRIPTION
**Pull request by coolacid**
This builds on #84 

Reverted all the flag bits, found the correct way todo this. Just adding the bootstrap5 class, and passing that to the template renderer does exactly what is needed. 

Moved, the example into different directories, this keeps the simple example unchanged, but adds a Bootstrap5 example version.

### CODE REVIEW

**Comment by qs5779** [comment]
My day just ended, I will look at this first thing tomorrow.

**Comment by coolacid** [comment]
I appreciate your time.

**Review by qs5779 — APPROVED** [review]
Looks goodl

**Comment by qs5779** [comment]
Published v0.7.2  at https://test.pypi.org/project/flask-nav3/  please verify all is well.

**Comment by coolacid** [comment]
Confirmed with my application I'm working on. Thanks!

**Pull request merged**
